from .expr_multiple import GraphMultipleExprOperation
from .expr_single import GraphSingleExprOperation
from .func_multiple import GraphMultipleFuncOperation
from .func_single import GraphSingleFuncOperation
from .parametric import GraphParametricOperation
from .rel_multiple import GraphMultipleRelOperation
from .rel_single import GraphSingleRelOperation
