name: CD
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Add remote to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to VM (exclude bot/data)
        run: |
          rsync -avz \
            -e "ssh" \
            --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "bot/data" \
            ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:DAS

      - name: Deploy application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p DAS
            cd DAS
            echo "${{ secrets.ENV_FILE }}" > bot/src/config/.env
            docker compose down
            docker compose up -d --build
            docker image prune -f 