name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: ./.github/actions/setup-python-env

      - name: Run unit tests
        run: |
          cd api
          python -m scripts.tests.run_tests

  integration:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up Python
        uses: ./.github/actions/setup-python-env

      - name: Run integration tests
        run: |
          cd api/app
          go test